import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: Define a CSS variable for easier use
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${inter.variable} bg-grayScale`}>
        <Header />
        <main className="h-min-screen mx-auto mt-[12vh] h-full w-5/6 max-w-[1440px]">
          {children}
        </main>
      </body>
    </html>
  );
}
